### ISSUE TITLE
Setting 'sudo' class parameters using yaml

### ISSUE THREAD

**Issue by hraphrap** [saz/puppet-sudo#114]
If I describe configuration via yaml files, i can't set sudo class parameters (here I want not to replace default configuration file /etc/sudoers). But i can't configure it through yaml.

```yaml
sudo:
    config_file_replace: false
sudo::configs:
    hraphrap:
        content: "hraphrap    ALL=(ALL) NOPASSWD: ALL"
```

in node definition:
```puppet
include sudo
```
puppet v3+
