### ISSUE TITLE
How can I add Cmnd_Alias

### ISSUE THREAD

**Issue by glafir** [saz/puppet-sudo#219]
Hellow!
How can I add Cmnd_Alias in module for example in sudoers config:

```
Cmnd_Alias APACHE_START = /usr/bin/service apache2 start
Cmnd_Alias APACHE_STOP = /usr/bin/service apache2 stop
Cmnd_Alias APACHE_RESTART = /usr/bin/service apache2 restart
Cmnd_Alias APACHE_RELOAD = /usr/bin/service apache2 reload
```

I did this in yaml
```
  sudo::configs:
    configs_hash:
      cmd_alias:
        priority: 5
        content:
        - 'Cmnd_Alias APACHE_START = /usr/bin/service apache2 start'
        - 'Cmnd_Alias APACHE_STOP = /usr/bin/service apache2 stop'
        - 'Cmnd_Alias APACHE_RESTART = /usr/bin/service apache2 restart'
        - 'Cmnd_Alias APACHE_RELOAD = /usr/bin/service apache2 reload'
```
But it didn`t work (((
