### ISSUE TITLE
I can't get sudo:defaults to work with hiera 

### ISSUE THREAD

**Issue by opentokix** [saz/puppet-sudo#308]
I have this block in hiera

```
sudo::defaults:
  use_pty:
  logfile: "/var/log/sudo.log"
  timestamp_timeout: 10
```
I have also tried this mentioned in the docs. 

```
sudo::defaults:
  use_pty:
  logfile: 
    value: "/var/log/sudo.log"
  timestamp_timeout: 
    value: 10
```

But those three default-lines does not get added to /etc/sudoers 

Puppet agent 8.6.0 
Puppetserver: 8.6.0 
OS: Ubuntu 22.04
